### PR TITLE
[SD-180] add search support to dropdowns

### PR DESCRIPTION
**Pull request by lambry**
**Issue**: https://digital-vic.atlassian.net/browse/SD-180

### What I did

- Adds search support to dropdowns

Test webform: https://app.pr-149.reference-sdp-vic-gov-au.sdp4.sdp.vic.gov.au/test-wf
Test search listing: https://app.pr-149.reference-sdp-vic-gov-au.sdp4.sdp.vic.gov.au/test-sl

#### Full dropdown component test suite

https://github.com/user-attachments/assets/479ff03a-383a-4a5f-af0f-1b397bf1bcd3

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed
- [ ] I've updated the documentation site as needed
- [x] I have added tests to cover my changes (if not applicable, please state why in a comment)

#### For new UI components only

- [ ] I have added a storybook story covering all variants
- [ ] I have checked a11y tab in storybook passes
- [x] I have added cypress component tests (if the component is interactive)
- [ ] Any events are emitted on the event bus using `emitRplEvent`

### CODE REVIEW

**Review by waitingallday — APPROVED** [review]
It all works 😄  I'm sure this has been done to death, but the only issue I have is with the ordering of selected elements - I would prefer it to list them in order of selection instead of sticking to list order. I'm sure there are reasons though.

**Comment by lambry** [comment]
> It all works 😄 I'm sure this has been done to death, but the only issue I have is with the ordering of selected elements - I would prefer it to list them in order of selection instead of sticking to list order. I'm sure there are reasons though.

Yeah that's just how the drop-downs currently work, but I think appearing in the order you selected would be better as well. I'll suggest it on the ticket.

Screenshot 2024-12-16 at 11 24 18 am

**Comment by dylankelly** [comment]
Another suggestion I'd make is to clear the search text input when you make a selection. At the moment you need to delete your input to make another search

https://github.com/user-attachments/assets/3092c108-d756-419c-bb1d-654abcc44ffa

**Comment by jeffdowdle** [comment]
👏 👏 👏

**Review by jeffdowdle — APPROVED** [review]

**Comment by lambry** [comment]
> Another suggestion I'd make is to clear the search text input when you make a selection. At the moment you need to delete your input to make another search
> 9dvzuz.mp4

Hey @dylankelly, I can see both ways here. 
For example, say you had a dropdown with several items relating to education, you type 'edu' then want to select the three related results, in this instance clearing the input would mean you would have to redo your search two more times, It's a trade off either way though. 

Also @waitingallday options now display in the order which they were selected. 👍

Cheers

**Review by dylankelly — APPROVED** [review]

**Pull request merged**
